name: pyscf-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pyscf
  - pandas
  - matplotlib
  - rdkit
  - py3dmol
  - jupyter
  - jupyterlab
  - ipywidgets
  - pip
  - pip:
    - git+https://github.com/funkymunkycool/Cube-Toolz.git
